# syntax=docker/dockerfile:1
FROM node:16-alpine
RUN apk add --no-cache git openssh-client
# Download public key for github.com
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_host
# Clone private repository
RUN --mount=type=ssh git clone git@github.com:myorg/myproject.git myproject